on: push
jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: buildx-${{ runner.os }}-${{ github.ref_name }}-${{ github.sha }}
          restore-keys: |
            buildx-${{ runner.os }}-${{ github.ref_name }}
            buildx-${{ runner.os }}-${{ github.event.repository.default_branch }}

      - name: Build linters and application images
        run: |
          docker compose -f envs/ci/docker-compose.yml --env-file envs/ci/.env build forum123-build
          docker compose -f envs/ci/docker-compose.yml --env-file envs/ci/.env build forum123-mypy
          docker compose -f envs/ci/docker-compose.yml --env-file envs/ci/.env build forum123-flake8
          docker compose -f envs/ci/docker-compose.yml --env-file envs/ci/.env build forum123-pylint

      - name: Run mypy
        run: docker compose -f envs/ci/docker-compose.yml --env-file envs/ci/.env run forum123-mypy

      - name: Run flake8
        run: docker compose -f envs/ci/docker-compose.yml --env-file envs/ci/.env run forum123-flake8

      - name: Run pylint
        run: docker compose -f envs/ci/docker-compose.yml --env-file envs/ci/.env run forum123-pylint

      # This ugly but it's necessary if you don't want your cache to grow forever
      # until it hits GitHub's limit of 5GB. Because `cache_to` option does not
      # update the entire Docker cache, but just adds some new layers.
      # This is a temporary fix. You can read more about this problem here:
      # https://github.com/docker/build-push-action/issues/252
      # https://github.com/moby/buildkit/issues/1896
      - name: Move cache
        run: |
          set -o allexport; source envs/ci/.env; set +o allexport;  # export environment variables from dotenv file
          rm -rf ${BUILDX_CACHE_SRC}
          mv ${BUILDX_CACHE_DEST} ${BUILDX_CACHE_SRC}
