# This workflow is used to remove old workflow runs which remained after force pushing a branch.
# More info about why we need this you can read in the according python script we run here.

on:
  push:
    branches-ignore:
      # we don't want to run cleaning up for these branches, because we expect them to never be force pushed
      - develop
jobs:
  cleanup-runs-for-rebased-branch:
    name: cleanup-runs-for-rebased-branch
    runs-on: ubuntu-latest
    steps:
      - name: Check out whole repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # fetch all history for all branches and tags

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"  # caching pip dependencies

      - name: Install dependencies
        run: pip install -r envs/ci/scripts/github/requirements.txt

      - name: Clean up workflow runs for current branch after rebase
        env:
          GITHUB_REF_NAME: ${{ vars.GITHUB_REF_NAME }}
          GITHUB_REPOSITORY: ${{ vars.GITHUB_REPOSITORY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python envs/ci/scripts/github/cleanup_runs_for_rebased_branch.py
