# This workflow is used to remove old workflow runs which remained after deleteing a branch.
# More info about why we need this you can read in the according python script we run here.`

on:
  delete  # runs when a git branch or tag is deleted
jobs:
  cleanup-runs-for-deleted-branch:
    name: cleanup-runs-for-deleted-branch
    if: github.event.ref_type == 'branch'
    runs-on: ubuntu-latest
    steps:
      - name: Check out whole repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # fetch all history for all branches and tags

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"  # caching pip dependencies

      - name: Install dependencies
        run: pip install -r envs/ci/scripts/github/requirements.txt

      - name: Clean up workflow runs for deleted branch
        env:
          GITHUB_EVENT_REF: ${{ github.event.ref }}  # we use `github.event.ref` here because `vars.GITHUB_REF_NAME`
                                                     # for deleted branch will point to default branch
          GITHUB_REPOSITORY: ${{ vars.GITHUB_REPOSITORY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python envs/ci/scripts/github/cleanup_runs_for_deleted_branch.py
